### PR TITLE
Replay events from a specific event store

### PR DESCRIPTION
**Pull request by mfullbrook**
Since #160 added the abilit to have event stores per aggregate root, this PR fixes the gap with the replay command so that we replay events from a specific store. Discussed in #162

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you!

**Comment by freekmurze** [comment]
Could you also send a PR to the documentation?

**Comment by mfullbrook** [comment]
You're welcome. Sure, I didn't see docs in the repo.

**Comment by freekmurze** [comment]
The docs aren't in this repo 😄 

You can create a PR for this page by click the edit button: https://docs.spatie.be/laravel-event-projector/v2/using-projectors/replaying-events

**Pull request merged**
